function data_out = importvelocity(filename, dataLines)
%IMPORTFILE Import data from a text file
%  M001HBASELINE1VELOCITY = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  M001HBASELINE1VELOCITY = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  M001HBaseline1velocity = importfile("D:\TinyDancers_Movement\DLC_output\M001_HBaseline_1_velocity.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Apr-2023 12:36:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["lefteye_x", "lefteye_y", "righteye_x", "righteye_y", "mouth_x", "mouth_y", "leftshoulder_x", "leftshoulder_y", "rightshoulder_x", "rightshoulder_y", "chest_x", "chest_y", "leftelbow_x", "leftelbow_y", "leftwrist_x", "leftwrist_y", "lefthand_x", "lefthand_y", "rightelbow_x", "rightelbow_y", "rightwrist_x", "rightwrist_y", "righthand_x", "righthand_y", "leftknee_x", "leftknee_y", "leftankle_x", "leftankle_y", "leftfoot_x", "leftfoot_y", "rightknee_x", "rightknee_y", "rightankle_x", "rightankle_y", "rightfoot_x", "rightfoot_y"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data_out = readtable(filename, opts);

end