function data_out = importvelocity(filename, dataLines)
%IMPORTFILE Import data from a text file
%  M001HBASELINE1VELOCITY = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  M001HBASELINE1VELOCITY = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  M001HBaseline1velocity = importfile("D:\TinyDancers_Movement\DLC_output\M001_HBaseline_1_velocity.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Apr-2023 12:36:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 36);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["lefteye", "righteye", "mouth", "leftshoulder", "rightshoulder", "chest", "leftelbow", "leftwrist", "lefthand", "rightelbow", "rightwrist", "righthand", "leftknee", "leftankle", "leftfoot", "rightknee", "rightankle", "rightfoot"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data_out = readtable(filename, opts);

end